[package]
name = "rewarder-hook"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-gen = { workspace = true }
anchor-lang = { workspace = true }
solana-sdk = { workspace = true }

[features]
no-entrypoint = []
